# Generated by Django 3.0.3 on 2020-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200310_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='Ruminating_Foraging',
            field=models.CharField(choices=[('Chewing', 'CHEWING'), ('Drinking', 'DRINKING'), ('Eating', 'EATING'), ('Licking', 'LICKING soil for minerals but did not eat'), ('None', 'None of the above'), ('Ruminating', 'RUMINATING')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='result',
            name='Video_Quality',
            field=models.CharField(choices=[('Excellent', 'EXCELLENT'), ('Good_to_Fair', 'GOOD to FAIR'), ('Poor', 'POOR'), ('Extremely_Obstructed', 'EXTREMELY OBSTRUCTED')], default='', max_length=20),
        ),
    ]
