# Generated by Django 3.0.3 on 2020-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20200310_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_insect_avoidance_behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='Does_the_cow_have_antlers',
            field=models.CharField(choices=[('cant see', "Can't see/Not sure/Not relevant"), ('No', 'No'), ('Yes', 'Yes')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='Is_a_calf_visible',
            field=models.CharField(choices=[('No', 'No'), ('Yes_her_own', 'Yes – her own'), ('Yes_possibly_her_own', 'Yes – possibly her own'), ('Yes_with_another_cow', 'Yes – with another cow')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='Other_caribou_visible_excluding_own_calf',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Yes_herd', 'Yes – herd'), ('Yes_one_to_a_few', 'Yes – one to a few individuals')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='State_of_Locomotion',
            field=models.CharField(choices=[('Napping', 'Napping'), ('Running', 'Running'), ('Stationary_Awake', 'Stationary Awake'), ('Wading/Swimming', 'Wading/Swimming'), ('Walking', 'Walking')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='Potential_insect_avoidance_behavior',
            field=models.ManyToManyField(to='analysis.Potential_insect_avoidance_behavior'),
        ),
    ]
