# Generated by Django 3.0.3 on 2020-03-10 21:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20200310_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='Habitat_features_visible',
            field=models.CharField(choices=[('Snow_cover_1–50%', 'Snow cover 1–50%'), ('Snow_cover_50–100%', 'Snow cover 50–100%'), ('Water', 'Water'), ('Burn_area', 'Burn area'), ('Human_signs', 'Human signs'), ('None', 'None of the above')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='What_is_the_PREDOMINANT_vegetation',
            field=models.CharField(choices=[('Poor_visibility', 'Poor visibility of predominant vegetation'), ('Alpine_Tundra', 'Alpine Tundra'), ('Lichen/Moss/Herbaceous', 'Lichen/Moss/Herbaceous'), ('Shrubby', 'Shrubby'), ('Forested–Deciduous', 'Forested – Deciduous'), ('Forested–Coniferous', 'Forested – Coniferous'), ('Unvegetated_Areas', 'Unvegetated Areas')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='result',
            name='What_part_of_the_habitat_is_visible',
            field=models.CharField(choices=[('Ground_immediate_surroundings', 'Ground and immediate surroundings'), ('None', 'None'), ('Only_ground', 'Only ground')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='result',
            name='Does_the_cow_have_antlers',
            field=models.CharField(choices=[('cant see', "Can't see/Not sure/Not relevant"), ('No', 'No'), ('Yes', 'Yes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='Is_a_calf_visible',
            field=models.CharField(choices=[('No', 'No'), ('Yes_her_own', 'Yes – her own'), ('Yes_possibly_her_own', 'Yes – possibly her own'), ('Yes_with_another_cow', 'Yes – with another cow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='Other_caribou_visible_excluding_own_calf',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Yes_herd', 'Yes – herd'), ('Yes_one_to_a_few', 'Yes – one to a few individuals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='Potential_insect_avoidance_behavior',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shook_its_head', 'Shook its head'), ('Kept_nose_Ground', 'Kept its nose still AND on the ground'), ('Scratched', 'Scratched'), ('Sought_snow_patch', 'Sought snow patch'), ('Huddled', 'Huddled'), ('None', 'None of the above')], max_length=72),
        ),
        migrations.AlterField(
            model_name='result',
            name='State_of_Locomotion',
            field=models.CharField(choices=[('Napping', 'Napping'), ('Running', 'Running'), ('Stationary_Awake', 'Stationary Awake'), ('Wading/Swimming', 'Wading/Swimming'), ('Walking', 'Walking')], max_length=20),
        ),
    ]
