# Generated by Django 3.0.3 on 2020-03-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20200323_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Cam_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='Week_Num',
            field=models.IntegerField(),
        ),
    ]
