# Generated by Django 3.0.3 on 2020-03-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_result_cam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='Cam_ID',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Week_Num',
        ),
    ]
