# Generated by Django 3.0.3 on 2020-03-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20200323_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='Cam_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='Date',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='result',
            name='Time',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='Week_Num',
            field=models.IntegerField(default=0),
        ),
    ]
